name: Build Standalone Apps
on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Tools
        run: |
          brew install tesseract poppler
          pip install PySide6 pytesseract pandas openpyxl pdf2image pyinstaller
          
      - name: Build App
        run: |
          TESS_PATH=$(which tesseract)
          POP_PATH=$(brew --prefix poppler)/bin
          
          pyinstaller --onefile --windowed \
            --add-binary "$TESS_PATH:." \
            --add-binary "$POP_PATH:poppler-library" \
            ticket_app.py

      - name: Upload Mac App
        uses: actions/artifact@v4
        with:
          name: TicketOCR-Mac
          path: dist/*.app
